# Automatically build and publish a release when a tag is pushed
name: release

on:
  push:
    tags:
      - 'v*' # triggers on version tags like v1.0.0, v2.1.3, etc.

jobs:
  release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write # needed to create releases
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: '22.0.2+9'
          distribution: 'temurin'
      
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      
      - name: build
        run: ./gradlew build
      
      - name: extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/libs/*.jar
          name: Release ${{ steps.version.outputs.VERSION }}
          tag_name: ${{ github.ref_name }}
          body: |
            ## Weekly World Mod v${{ steps.version.outputs.VERSION }}
            
            ### Changes
            - Auto-generated release from tag ${{ github.ref_name }}
            
            ### Installation
            1. Download the `.jar` file from the assets below
            2. Place it in your `mods` folder
            3. Make sure you have Fabric Loader installed
            
            ### Requirements
            - Minecraft 1.21+
            - Fabric Loader
            - Fabric API
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
