# Automatically build and publish a release when a tag is pushed
name: release

on:
  push:
    tags:
      - "v*" # triggers on version tags like v1.0.0, v2.1.3, etc.

jobs:
  release:
    runs-on: ubuntu-24.04
    permissions:
      contents: write # needed to create releases
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: "22.0.2+9"
          distribution: "temurin"

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew build

      - name: extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: get jar hashes
        id: hashes
        run: |
          for file in build/libs/*.jar; do
            # exclude sources
            if [[ "$file" == *-sources.jar ]]; then
              continue
            fi
            # calculate hashes
            sha1=$(sha1sum "$file" | awk '{print $1}')
            echo "sha1: $sha1" >> $GITHUB_OUTPUT

            sha512=$(sha512sum "$file" | awk '{print $1}')
            echo "sha512: $sha512" >> $GITHUB_OUTPUT
          done

      - name: create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/libs/*.jar
          name: Release ${{ steps.version.outputs.VERSION }}
          tag_name: ${{ github.ref_name }}
          body: |
            ## Weekly World Mod v${{ steps.version.outputs.VERSION }}

            ### JAR Hashes
            - sha1: ${{ steps.hashes.outputs.sha1 }}
            - sha512: ${{ steps.hashes.outputs.sha512 }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
